//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RefugeeHousing.Resources.LocalizedText", typeof(LocalizedText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new listing.
        /// </summary>
        public static string AddNewListing {
            get {
                return ResourceManager.GetString("AddNewListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Property.
        /// </summary>
        public static string AddProperty {
            get {
                return ResourceManager.GetString("AddProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Properties.
        /// </summary>
        public static string AllProperties {
            get {
                return ResourceManager.GetString("AllProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliances included.
        /// </summary>
        public static string AppliancesIncluded {
            get {
                return ResourceManager.GetString("AppliancesIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Fridge, Dishwasher, etc..
        /// </summary>
        public static string AppliancesIncludedPlaceholder {
            get {
                return ResourceManager.GetString("AppliancesIncludedPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refugee Housing.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Properties.
        /// </summary>
        public static string AvailableProperties {
            get {
                return ResourceManager.GetString("AvailableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedrooms.
        /// </summary>
        public static string Bedrooms {
            get {
                return ResourceManager.GetString("Bedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact property owner.
        /// </summary>
        public static string ContactFormHeader {
            get {
                return ResourceManager.GetString("ContactFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete listing.
        /// </summary>
        public static string DeleteListingConfirmation {
            get {
                return ResourceManager.GetString("DeleteListingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevator.
        /// </summary>
        public static string Elevator {
            get {
                return ResourceManager.GetString("Elevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnglishLanguage {
            get {
                return ResourceManager.GetString("EnglishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address.
        /// </summary>
        public static string EnquirerEmailAddress {
            get {
                return ResourceManager.GetString("EnquirerEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string EnquirerName {
            get {
                return ResourceManager.GetString("EnquirerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///You have a query regarding your property from {0}, on behalf of the organization &apos;{1}&apos;.
        ///
        ///For more details on the organization, visit {2}
        ///
        ///Languages spoken by {0}: {3}
        ///
        ///This person has expressed their willingness to sign medium-to-long-term leases on behalf of refugee families, and to pay first and last month&apos;s rent up front..
        /// </summary>
        public static string EnquiryEmail {
            get {
                return ResourceManager.GetString("EnquiryEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furnished.
        /// </summary>
        public static string Furnished {
            get {
                return ResourceManager.GetString("Furnished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        public static string GreekLanguage {
            get {
                return ResourceManager.GetString("GreekLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages spoken.
        /// </summary>
        public static string LanguagesSpoken {
            get {
                return ResourceManager.GetString("LanguagesSpoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Greek, English, etc..
        /// </summary>
        public static string LanguagesSpokenPlaceholder {
            get {
                return ResourceManager.GetString("LanguagesSpokenPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your address.
        /// </summary>
        public static string LocationPlaceholder {
            get {
                return ResourceManager.GetString("LocationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Properties.
        /// </summary>
        public static string MyProperties {
            get {
                return ResourceManager.GetString("MyProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results Found.
        /// </summary>
        public static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of bedrooms.
        /// </summary>
        public static string NumberOfBedrooms {
            get {
                return ResourceManager.GetString("NumberOfBedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization name.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to find more information about your organisation, e.g. your website or Facebook page.
        /// </summary>
        public static string OrganizationWebsite {
            get {
                return ResourceManager.GetString("OrganizationWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price listed is the rental price per month.
        /// </summary>
        public static string PriceGivenPerMonth {
            get {
                return ResourceManager.GetString("PriceGivenPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per month.
        /// </summary>
        public static string PricePerMonth {
            get {
                return ResourceManager.GetString("PricePerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Details.
        /// </summary>
        public static string PropertyDetails {
            get {
                return ResourceManager.GetString("PropertyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages spoken by property owner.
        /// </summary>
        public static string PropertyOwnerLanguages {
            get {
                return ResourceManager.GetString("PropertyOwnerLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new listing.
        /// </summary>
        public static string RegisterNewListing {
            get {
                return ResourceManager.GetString("RegisterNewListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Enquiry.
        /// </summary>
        public static string SubmitEnquiry {
            get {
                return ResourceManager.GetString("SubmitEnquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree that this property can be rented to refugees.
        /// </summary>
        public static string WillRentToRefugees {
            get {
                return ResourceManager.GetString("WillRentToRefugees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On behalf of my organisation, I agree that we are willing to sign a lease on behalf of a refugee family, and to pay the first and last month&apos;s rent up front.
        /// </summary>
        public static string WillSignContract {
            get {
                return ResourceManager.GetString("WillSignContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
